#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APP_DIR="/var/www/fortcordis-stage"
BRANCH="stage"
BACKEND_SERVICE="fortcordis-stage-backend"
FRONTEND_SERVICE="fortcordis-stage-frontend"
BACKEND_PORT="8001"
FRONTEND_PORT="3001"
API_BACKEND_URL="http://127.0.0.1:8001"
PUBLIC_URL="https://stage.fortcordis.com.br"
ENABLE_WHATSAPP_STAGE_BACKEND="1"
WHATSAPP_STAGE_BACKEND_SERVICE="fortcordis-stage-whatsapp-backend"
WHATSAPP_STAGE_BACKEND_PORT="3010"
WHATSAPP_STAGE_BACKEND_URL="http://127.0.0.1:${WHATSAPP_STAGE_BACKEND_PORT}"
ENABLE_WHATSAPP_STAGE_SMOKE="1"
WHATSAPP_REQUIRE_DISTINCT_FROM_PRODUCTION="1"
ENABLE_ECO_STUDY_OCR="1"
REQUIRE_ECO_STUDY_OCR="1"
# O inventario de 2026-09-06 confirmou os quatro vhosts no mesmo listener
# 0.0.0.0:443. A autorizacao explicita cobre o conjunto atomico completo.
ENABLE_NGINX_HTTP2="1"
NGINX_HTTP2_EXPECTED_HOSTS="app.stage.fortcordis.com.br,app.fortcordis.com.br,fortcordis.com.br,fortcordis.com"

export APP_DIR BRANCH BACKEND_SERVICE FRONTEND_SERVICE BACKEND_PORT FRONTEND_PORT API_BACKEND_URL PUBLIC_URL \
  ENABLE_WHATSAPP_STAGE_BACKEND WHATSAPP_STAGE_BACKEND_SERVICE WHATSAPP_STAGE_BACKEND_PORT \
  WHATSAPP_STAGE_BACKEND_URL ENABLE_WHATSAPP_STAGE_SMOKE WHATSAPP_REQUIRE_DISTINCT_FROM_PRODUCTION
export ENABLE_ECO_STUDY_OCR REQUIRE_ECO_STUDY_OCR
export ENABLE_NGINX_HTTP2 NGINX_HTTP2_EXPECTED_HOSTS

bash "${SCRIPT_DIR}/deploy_prod_vps.sh"
