const RACAS_POR_ESPECIE: Record<string, string[]> = {
  Canina: [
    "SRD",
    "Akita",
    "American Pitbull",
    "Australian Shepherd",
    "Beagle",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Border Collie",
    "Boston Terrier",
    "Boxer",
    "Bull Terrier",
    "Cairn Terrier",
    "Cane Corso",
    "Cavalier King Charles Spaniel",
    "Chihuahua",
    "Chow Chow",
    "Cocker Spaniel",
    "Dachshund",
    "Doberman",
    "Dogue Alemao",
    "Fox Terrier",
    "Galgo",
    "Golden Retriever",
    "Great Dane",
    "Husky Siberiano",
    "Jack Russell Terrier",
    "Labrador Retriever",
    "Lhasa Apso",
    "Maltes",
    "Mastiff",
    "Newfoundland",
    "Pastor Alemao",
    "Pastor Belga",
    "Pinscher",
    "Poodle",
    "Pug",
    "Rottweiler",
    "Saint Bernard",
    "Samoieda",
    "Scottish Terrier",
    "Shetland Sheepdog",
    "Shih Tzu",
    "Shar Pei",
    "Spitz Alemao",
    "Springer Spaniel",
    "Staffordshire Bull Terrier",
    "Weimaraner",
    "West Highland White Terrier",
    "Whippet",
    "Yorkshire Terrier",
  ],
  Felina: [
    "SRD",
    "Abissinio",
    "American Shorthair",
    "Angora",
    "Balinese",
    "Bengal",
    "Birmanes",
    "British Shorthair",
    "Burmese",
    "Chartreux",
    "Cornish Rex",
    "Devon Rex",
    "European Shorthair",
    "Exotico Shorthair",
    "Havana Brown",
    "Korat",
    "Maine Coon",
    "Norwegian Forest",
    "Oriental Shorthair",
    "Persa",
    "Pixie Bob",
    "Ragdoll",
    "Russo Azul",
    "Savannah",
    "Scottish Fold",
    "Siamese",
    "Somali",
    "Sphynx",
    "Tonquines",
  ],
  Equina: [
    "SRD",
    "Quarto de Milha",
    "Mangalarga Marchador",
    "Crioulo",
    "Puro Sangue Ingles",
    "Appaloosa",
  ],
  Outra: ["SRD"],
};

const DEFAULT_RACAS = ["SRD"];

export function getRacaOptions(especie?: string, racaAtual?: string): string[] {
  const base = RACAS_POR_ESPECIE[especie || ""] || DEFAULT_RACAS;
  const atual = (racaAtual || "").trim();
  if (atual && !base.includes(atual)) {
    return [atual, ...base];
  }
  return base;
}
